### ISSUE TITLE
Just a suggestion and thought for a compass

### ISSUE THREAD

**Issue by bqytallhsirlkm** [metinkale38/prayer-times-android#159]
**Alsalam Alikum,**
after my experience of the application and reading the code for the application, I found that the application is great and thanks a lot to the developer. There is a good thought of the compass, which is the addition of many places such as the shrine of the Prophet Muhammad, may God bless him and his family, and another Islamic shrine, etc...
So that the user can determine the location in the compass.

Also, I found the (3D-AR) compass doesn't work.

**Allah Blass you**

**Comment by metinkale38** [comment]
Alaikum salam,

First at all i removed the 3D-AR Compass myself because it seemed to not very accurate compared to the 2D Compass. For prayer we should try to rely on the most accurate methods.

Its seems to be the implementation, because Google released a AR-Prayer-Compass which is very accurate (open g.co/qiblafinder on your phone).

Because it is a Compass for finding Prayer Direction, i actually so no reason to add other places to it, it might would be a "nice to have" but without real use-case...
