### ISSUE TITLE
Cannot activate "show minutes in notification icon"

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#65]
I cannot activate "show minutes in notification icon".
The following options are activated:
"Notification Icon" and "alternative notification icon"

Best regards

**Comment by metinkale38** [comment]
the "show minutes in notification icon" uses android apis (https://developer.android.com/reference/android/graphics/drawable/Icon.html) which are available since API Level 23 (Android 6.0)

for versions below, this option is disabled.

Some manufacturer firmwares (specially Samsung on some phones) do not support this API, even if they are on Android 6.0. 
For this case the option is not disabled, but will be automatically disabled, if it will fail.
