### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jobbb** [metinkale38/prayer-times-android#68]
1. Please can you tell me, when i should use the option "use arabic prayertimes"?
The option is deactivated and the prayertimes for Morocco are OK! What does this option do?
2. Do you have a option for summer- and wintertime?

Best regards

**Comment by metinkale38** [comment]
1.) This function changes the texts for "Fajr, Zuhr, Asr,..." into arabic letters.

Now, since arabic language support is added, its not really needed, but some people might still want to use that.

If you use a web prayer times source (diyanet, igmg, habous.gov.ma etc.) they have to take care of updating the times according summer and wintertime.
if you use the calculated prayer times, it will use the timezone of your phone, if this one is set, everything should be fine.

So you normally dont have to change anyhing for summer and wintertime, but if it is wrong, you can shift the time by for example 1 hour by swiping down from the most top.

**Comment by jobbb** [comment]
Thank you for your answers!
Best regards.
