### ISSUE TITLE
Suggestion ismaeli dates and prayers

### ISSUE THREAD

**Issue by piks3l** [metinkale38/prayer-times-android#98]
Hi! Would you consider adding ismaeli prayers and dates or like settings for the app for this branch of Islam? 

Best

**Comment by metinkale38** [comment]
Hi,

this App is mainly developed according to Sunni Islam, but of course everyone can use it, but i do not plan to add special features for all groups.

After some googling i read, that Ismailis only Pray 3 Times a Day instead of 5. That also would break the whole concept and would need some effort.
I do not know much about Ismailism, but if it helps: if you select calculated Prayer Times you can also select the calculation Method of the University of Tehran oder the Leva Research Institute which are used in Iran or other Shia communities...
